name: Update Data

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: Scripts
        run: npm clean-install

      - name: Run npm script
        working-directory: Scripts
        run: npm run generate-data

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Data/v1.json
          git commit -m "chore: update data\n\n[skip ci]" || echo "No changes to commit"
          git push
